import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 1400, height: 1200 }, deviceScaleFactor: 2 })
await page.goto('http://localhost:5173')
await page.waitForTimeout(300)
await page.locator('.landing-proof-stat').scrollIntoViewIfNeeded()
await page.waitForTimeout(600)
const card1 = page.locator('.landing-proof-card--before')
await card1.screenshot({ path: '/tmp/card1-rest.png' })
await card1.hover()
await page.waitForTimeout(700)
await card1.screenshot({ path: '/tmp/card1-hover.png' })
const card2 = page.locator('.landing-proof-card--after')
await card2.hover()
await page.waitForTimeout(700)
await card2.screenshot({ path: '/tmp/card2-hover.png' })
await browser.close()
