// A one-line cultural identity per SF Analysis Neighborhood (41) — "what is
// this place known for." Static human knowledge, NOT trajectory data: it never
// changes with permits/units, so it lives here rather than on the API feature.
// Keys must match the `nhood` values in sf_neighborhoods.geojson exactly.
// Kept deliberately terse (a few words) — the hover is a scent, not a summary.
export const KNOWN_FOR: Record<string, string> = {
  'Bayview Hunters Point': 'Shipyard arts & industry',
  'Bernal Heights': 'Hilltop village & views',
  'Castro/Upper Market': 'LGBTQ heart of the city',
  Chinatown: 'Oldest Chinatown in the US',
  Excelsior: 'Diverse working-class enclave',
  'Financial District/South Beach': 'Downtown towers & the ballpark',
  'Glen Park': 'Village feel & canyon trails',
  'Golden Gate Park': "The city's great park",
  'Haight Ashbury': 'Home of the Summer of Love',
  'Hayes Valley': 'Boutiques & the arts',
  'Inner Richmond': 'Clement Street eats',
  'Inner Sunset': 'Foggy streets by the park',
  Japantown: 'Historic Japantown',
  Lakeshore: 'Lake Merced & SF State',
  'Lincoln Park': 'Legion of Honor & coastal golf',
  'Lone Mountain/USF': 'University hill',
  Marina: 'Waterfront & Palace of Fine Arts',
  'McLaren Park': "The city's wild second park",
  Mission: 'Murals, taquerias & nightlife',
  'Mission Bay': 'UCSF & the Chase Center',
  'Nob Hill': 'Grand hotels atop the hill',
  'Noe Valley': 'Sunny, stroller-friendly slopes',
  'North Beach': 'Italian cafés & Beat history',
  'Oceanview/Merced/Ingleside': 'Quiet southwest neighborhoods',
  'Outer Mission': 'Residential & multicultural',
  'Outer Richmond': 'Ocean Beach & the fog',
  'Pacific Heights': 'Mansions & bay views',
  Portola: "The city's old garden district",
  'Potrero Hill': 'Sunny hilltop & design studios',
  Presidio: 'Forested former army post',
  'Presidio Heights': 'Leafy, quiet & moneyed',
  'Russian Hill': "Lombard's crooked street",
  Seacliff: 'Cliffside mansions by the sea',
  'South of Market': 'Tech, clubs & warehouses',
  'Sunset/Parkside': 'Foggy avenues to the ocean',
  Tenderloin: 'Gritty, dense & historic',
  'Treasure Island': 'Man-made island, skyline views',
  'Twin Peaks': 'Twin summits & citywide views',
  'Visitacion Valley': 'Quiet southeast corner',
  'West of Twin Peaks': 'Leafy hillside residential',
  'Western Addition': 'Fillmore jazz heritage',
}
